sudo: false
addons:
  apt:
    packages:
    - git
language: groovy
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.sonar/cache"
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_install:
- git fetch --unshallow || true
- git config user.email "rene.neubert@softcake.org"
- git config user.name "Travis-CI"
- git config url.https://.insteadOf git://
- git checkout -qf $TRAVIS_BRANCH
install:
- echo "skip default gradlew assemble"
script:
- "./travis-build.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  matrix:
  - TERM=dumb
  global:
